--
-- PostgreSQL database dump
--

-- Dumped from database version 17.5
-- Dumped by pg_dump version 17.5

-- Started on 2025-06-23 01:16:33

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 224 (class 1259 OID 16600)
-- Name: exams; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.exams
(
    exam character varying(255) NOT NULL
);


ALTER TABLE public.exams
    OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 16389)
-- Name: game_room; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.game_room
(
    room_code              character varying(32) NOT NULL,
    current_question_index integer,
    started                boolean,
    host_id                character varying(255),
    question_duration      integer,
    option_count           integer,
    level                  character varying(255),
    total_question_count   integer,
    last_used              timestamp(6) without time zone,
    hashed_password        character varying(128)
);


ALTER TABLE public.game_room
    OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 16394)
-- Name: player; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.player
(
    id                character varying(255) NOT NULL,
    room_code         character varying(32),
    name              character varying(255),
    score             integer,
    correct_count     integer,
    wrong_count       integer,
    total_answer_time bigint,
    avatar_id         integer
);


ALTER TABLE public.player
    OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 16412)
-- Name: player_answer; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.player_answer
(
    id                    bigint NOT NULL,
    player_id             character varying(255),
    question_id           character varying(255),
    selected_option_index integer,
    correct               boolean,
    answer_time_ms        bigint
);


ALTER TABLE public.player_answer
    OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 16411)
-- Name: player_answer_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.player_answer_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.player_answer_id_seq OWNER TO postgres;

--
-- TOC entry 4956 (class 0 OID 0)
-- Dependencies: 220
-- Name: player_answer_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.player_answer_id_seq OWNED BY public.player_answer.id;


--
-- TOC entry 219 (class 1259 OID 16404)
-- Name: question; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.question
(
    id            character varying(255) NOT NULL,
    text          character varying(255),
    options       text[],
    correct_index integer
);


ALTER TABLE public.question
    OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 16450)
-- Name: question_options; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.question_options
(
    question_id character varying(255) NOT NULL,
    options     character varying(255)
);


ALTER TABLE public.question_options
    OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 16606)
-- Name: statistics; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.statistics
(
    stat_id       integer NOT NULL,
    correct_count integer,
    learned       boolean,
    skipped_count integer,
    wrong_count   integer
);


ALTER TABLE public.statistics
    OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 16605)
-- Name: statistics_stat_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.statistics
    ALTER COLUMN stat_id ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.statistics_stat_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
        );


--
-- TOC entry 227 (class 1259 OID 16611)
-- Name: word_exam_cross_ref; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.word_exam_cross_ref
(
    exam character varying(255) NOT NULL,
    word character varying(255) NOT NULL
);


ALTER TABLE public.word_exam_cross_ref
    OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 16517)
-- Name: words; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.words
(
    word          character varying(255) NOT NULL,
    level         character varying(255),
    meaning       character varying(255),
    last_reviewed bigint,
    seconds_spent integer,
    stat_id       integer
);


ALTER TABLE public.words
    OWNER TO postgres;

--
-- TOC entry 4775 (class 2604 OID 16434)
-- Name: player_answer id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.player_answer
    ALTER COLUMN id SET DEFAULT nextval('public.player_answer_id_seq'::regclass);


--
-- TOC entry 4947 (class 0 OID 16600)
-- Dependencies: 224
-- Data for Name: exams; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.exams (exam) FROM stdin;
\.


--
-- TOC entry 4940 (class 0 OID 16389)
-- Dependencies: 217
-- Data for Name: game_room; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.game_room (room_code, current_question_index, started, host_id, question_duration, option_count, level,
                       total_question_count, last_used, hashed_password) FROM stdin;
\.


--
-- TOC entry 4941 (class 0 OID 16394)
-- Dependencies: 218
-- Data for Name: player; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.player (id, room_code, name, score, correct_count, wrong_count, total_answer_time, avatar_id) FROM stdin;
\.


--
-- TOC entry 4944 (class 0 OID 16412)
-- Dependencies: 221
-- Data for Name: player_answer; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.player_answer (id, player_id, question_id, selected_option_index, correct, answer_time_ms) FROM stdin;
\.


--
-- TOC entry 4942 (class 0 OID 16404)
-- Dependencies: 219
-- Data for Name: question; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.question (id, text, options, correct_index) FROM stdin;
q1	Translate: Apple	{Elma,Armut,Karpuz,Muz}	0
\.


--
-- TOC entry 4945 (class 0 OID 16450)
-- Dependencies: 222
-- Data for Name: question_options; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.question_options (question_id, options) FROM stdin;
\.


--
-- TOC entry 4949 (class 0 OID 16606)
-- Dependencies: 226
-- Data for Name: statistics; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.statistics (stat_id, correct_count, learned, skipped_count, wrong_count) FROM stdin;
\.


--
-- TOC entry 4950 (class 0 OID 16611)
-- Dependencies: 227
-- Data for Name: word_exam_cross_ref; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.word_exam_cross_ref (exam, word) FROM stdin;
\.


--
-- TOC entry 4946 (class 0 OID 16517)
-- Dependencies: 223
-- Data for Name: words; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.words (word, level, meaning, last_reviewed, seconds_spent, stat_id) FROM stdin;
\.


--
-- TOC entry 4957 (class 0 OID 0)
-- Dependencies: 220
-- Name: player_answer_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.player_answer_id_seq', 1, false);


--
-- TOC entry 4958 (class 0 OID 0)
-- Dependencies: 225
-- Name: statistics_stat_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.statistics_stat_id_seq', 1, false);


--
-- TOC entry 4787 (class 2606 OID 16604)
-- Name: exams exams_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exams
    ADD CONSTRAINT exams_pkey PRIMARY KEY (exam);


--
-- TOC entry 4777 (class 2606 OID 16393)
-- Name: game_room game_room_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.game_room
    ADD CONSTRAINT game_room_pkey PRIMARY KEY (room_code);


--
-- TOC entry 4783 (class 2606 OID 16436)
-- Name: player_answer player_answer_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.player_answer
    ADD CONSTRAINT player_answer_pkey PRIMARY KEY (id);


--
-- TOC entry 4779 (class 2606 OID 16426)
-- Name: player player_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.player
    ADD CONSTRAINT player_pkey PRIMARY KEY (id);


--
-- TOC entry 4781 (class 2606 OID 16449)
-- Name: question question_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.question
    ADD CONSTRAINT question_pkey PRIMARY KEY (id);


--
-- TOC entry 4789 (class 2606 OID 16610)
-- Name: statistics statistics_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.statistics
    ADD CONSTRAINT statistics_pkey PRIMARY KEY (stat_id);


--
-- TOC entry 4791 (class 2606 OID 16617)
-- Name: word_exam_cross_ref word_exam_cross_ref_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.word_exam_cross_ref
    ADD CONSTRAINT word_exam_cross_ref_pkey PRIMARY KEY (exam, word);


--
-- TOC entry 4785 (class 2606 OID 16523)
-- Name: words words_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.words
    ADD CONSTRAINT words_pkey PRIMARY KEY (word);


--
-- TOC entry 4794 (class 2606 OID 16455)
-- Name: question_options fkjk4v42xhyfv4ca1yyhorsg5tv; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.question_options
    ADD CONSTRAINT fkjk4v42xhyfv4ca1yyhorsg5tv FOREIGN KEY (question_id) REFERENCES public.question (id);


--
-- TOC entry 4793 (class 2606 OID 16441)
-- Name: player_answer player_answer_player_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.player_answer
    ADD CONSTRAINT player_answer_player_id_fkey FOREIGN KEY (player_id) REFERENCES public.player (id);


--
-- TOC entry 4792 (class 2606 OID 16399)
-- Name: player player_room_code_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.player
    ADD CONSTRAINT player_room_code_fkey FOREIGN KEY (room_code) REFERENCES public.game_room (room_code);


-- Completed on 2025-06-23 01:16:33

--
-- PostgreSQL database dump complete
--

